### ISSUE TITLE
[Bug]:  Form validation issue in "Age" field .

### ISSUE THREAD

**Issue by akash70629** [apurakshit2001/free-codecamp--survey#1]
**Is your feature request related to a problem? Please describe.**
The age field accepts ages from 0 to 100. The minimum age should be at least 10.

**Describe the solution you'd like.**
We can modify the minimum age validation.

**To Reproduce the problem**

1. Go to the Home page and see the "Age" field.

**Additional context**
![image](https://github.com/apurakshit2001/free-codecamp--survey/assets/76689571/7dcbe504-c07c-4d6a-ade0-6b6bc43124f1)

**Please checkmark the following checklist**

- [x] I make sure that a similar issue is not opened

**Comment by apurakshit2001** [comment]
Thank you very much
